### ISSUE TITLE
Non-date(time) x-values are converted to dates

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/autospc#19]
At present if a dataframe with x of type integer (for example) is passed into `plot_auto_SPC`, that column x is converted to date. There is no reason why the horizontal axis needs to be a date (or datetime), provided it is ordered. It would be good to allow the code to handle any ordered x.

If this is more complex and might take a while, then in the mean time having a warning issued if x is neither a date nor a date time would help.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom, I realised why I hadn't put in the pull request for this... I've done the method that we talked about and it's working for everything apart from dates now and I'm not sure how I managed to break that part.  I'm going to look at it with fresh eyes next week because it feels like it should be a simple fix as it's working with dates on master!

**Comment by HorridTom** [comment]
@ImogenConnorHelleur I think this one is complete now, can we close it?
