### ISSUE TITLE
Adjust display limits for P and P' charts to factor in volumes.

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/autospc#5]

**Comment by HorridTom** [comment]
@ImogenConnorHelleur just checking on this one - how are the display limits established at present?

**Comment by ImogenConnorHelleur** [comment]
At the moment they just take the last value of the calculation period limits and copy that across.

**Comment by HorridTom** [comment]
Ok that makes sense - I think this is one that we should bump up the priority list - I just ran an example and because the last point had a relatively small denominator, the limits into the display period were unusually wide... More of a problem with data that have widely varying denominators, or smaller denominators... I'll mark as high priority - and I don't mind having a look?

**Comment by ImogenConnorHelleur** [comment]
I agree.  I did try to do this a while back but can't remember why it wasn't working for me so would be good for you to have a look thanks.

**Comment by HorridTom** [comment]
I think the correct behaviour for p-charts should be that the display limits should use the actual denominators for the display period, but the same average p (proportion) from the calculation period. I.e. in the p-chart limit formula, the "n" should come from the display period, but the "p-bar" should come from the calculation period...

**Comment by HorridTom** [comment]
Ok sure - I'll take a look!
