### ISSUE TITLE
Edge case to discuss

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/autospc#57]
![image](https://user-images.githubusercontent.com/31736674/156764035-ca64db52-d373-4a72-8b2e-a05eac10a3dc.png)

**Comment by HorridTom** [comment]
Hi @ImogenConnorHelleur hmmm this is odd - I would have thought this would recalculate from the start of the second rule break as shown (~29th point?) - doesn't look by eye like there'd be a rule-breaking run in the opposite direction??

**Comment by HorridTom** [comment]
@ImogenConnorHelleur are you ok to try this with the latest version of the package as currently on master? If still behaving like this, is there any way you can share this dataset at aggregate anonymised level so that I can reproduce?

**Comment by HorridTom** [comment]
> Hi @HorridTom , interestingly I've tried this out on my NHS laptop again after uninstalling and reinstalling the package pointing at the most recent commit and it looks like the aesthetic changes have updated but it is still not recalculating.
> 
> It's not patient level or sensitive data so I've sent it to my personal machine where it does recalculate as expected! I think the issue lies with my NHS laptop's version of rtools because I don't think it's building the package correctly. I think we can go ahead and delete this issue.
That is very odd isn't it... I'd be surprise if RTools is the issue because I'd expect it to either work or throw an error... but it could be that I suppose. It might be worth us digging a little longer, just in case this is a subtle bug...

On your NHS laptop, are you running this within an RStudio project, or just outside a project? Something I found useful when debugging the linetype problem before, was making a new RStudio project with renv enabled, then `install_github`ing autospc into that "fresh" project (since this isolates it from all the package versions you have in your global library). Have you tried that? If not, might be worth a go... And if it recalculates then, it probably means it is to do with the package versions installed in your global library on the NHS machine.... In which case, we should have a version > X in the DESCRIPTION file, to make sure this isn't happening for users. If it still doesn't recalculate, that's more convincing that it's something like RTools or other external dependency... Apologies if you've already tried this... just a thought!
