### ISSUE TITLE
Issue with merged branch for plot aesthetics

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/autospc#59]
Hi @HorridTom, my fault for not checking enough cases. I installed the latest version of the package and got this:
![image](https://user-images.githubusercontent.com/31736674/157300268-f5f39237-19a8-4217-a340-83d2826ae922.png)

I'll make a new branch now to fix.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom , this actually might be a false alarm. I've tried to reproduce the problem on my personal laptop with the same data and I'm not getting the invisible lines...

My thoughts are that I might not have an up-to-date ggplot (or other packages) on my NHS laptop and it's not recognising the custom line type for the display period. 

I'll look into this further but I don't think it's a bug on our end.

**Comment by HorridTom** [comment]
Ok thanks @ImogenConnorHelleur - and this problem was when you `install.packages("autospc")` and then run `plot_auto_spc`? (rather than install and restart from the build menu inside a clone of the repo?) If the former, and if as you say it is related to the version of ggplot, that probably means we should update the versions in the `Imports:` section of the DESCRIPTION file... although looking at it, we already ask for ggplot (>= 3.3.3), and current version is 3.3.5 so not far off. But could be another package I suppose... We should try installing it in a few more repos/on a few more machines and see if we can replicate the problem. Is this dataset (or a slightly perturbed one that gives the same result) possible to share for this purpose?

**Comment by HorridTom** [comment]
Ah, no, I'm getting this issue too.. this is using `plot_auto_spc` with `df` equal to the data frame in tests/testthat/testdata/test_data.rds

![test-data-bug](https://user-images.githubusercontent.com/8202350/157434124-c59ebb3b-693e-4e02-be0d-d7699bd4ec58.png)
.

**Comment by HorridTom** [comment]
I think the problem has something to do with the `breaks` argument in `scale_linetype_manual`... commenting this out makes the limits reappear, but messes up the legend...

**Comment by HorridTom** [comment]
Hi @ImogenConnorHelleur I think I've found a fix for this. I will make a new branch for this issue and commit for you to review.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom , I've tried reinstalling the package (pointing at the new branch) on my work laptop and I'm still getting the bug. Does it work for you when you install it as a package from outside the package environment?

The fixes in the pull request make sense to me so I'm not sure why it's not updating for me. I'll try again tomorrow on my personal laptop.
